-- MEETS start-stage admin authentication
--
-- Active login:
--   public.meets_admin_password_login(p_email text, p_password text)
--
-- One-time initial setup:
--   public.meets_admin_password_ready()
--   public.meets_admin_setup_password(p_email text, p_recovery_code text, p_password text)
--   setup consumes the existing emergency recovery code and stores only a bcrypt hash.
--
-- Private credential storage:
--   meets_private.admin_password_credentials
--
-- Security properties:
-- - approved email stored only as SHA-256 hash;
-- - password stored only as bcrypt hash (pgcrypto crypt/gen_salt);
-- - five failed attempts lock login for 15 minutes;
-- - successful login resets the failed-attempt counter;
-- - successful login issues the existing short-lived MEETS admin session token;
-- - credential table is not readable by anon/authenticated roles.
--
-- Google/OTP/recovery flows are not part of the active start-stage UI.
-- When the project matures, stronger authentication can replace this login
-- without changing downstream admin session RPCs.
--
-- Apply production changes through reviewed migrations.
