-- MEETS admin authentication
-- Production uses a custom six-digit OTP challenge delivered with Resend.
-- The Resend sending-only API key is stored in Supabase Vault under:
--   meets_resend_api_key
--
-- The production migration creates:
--   meets_private.admin_otp_settings
--   meets_private.admin_otp_challenges
--   meets_private.request_admin_email_otp(text)
--   meets_private.verify_admin_email_otp(uuid,text)
--   public.meets_admin_request_otp(text)
--   public.meets_admin_verify_otp(uuid,text)
--
-- Key properties:
-- - only the SHA-256 hash of the approved login email is stored;
-- - codes expire after 10 minutes;
-- - maximum five failed verification attempts;
-- - resend limited to once per 60 seconds;
-- - code hashes and session-token hashes are stored, never plaintext values;
-- - Supabase Auth Magic Link/password login is not part of the MEETS admin flow.
--
-- Current production functions should be inspected with pg_get_functiondef
-- before changing this file into an executable migration. Database changes
-- must be applied through versioned migrations, not ad-hoc DDL.
