-- MEETS admin authentication architecture
--
-- 1. Primary: Google OAuth through Supabase Auth.
--    public.meets_admin_google_exchange()
--    - requires authenticated role;
--    - requires auth.uid();
--    - requires a verified Google identity;
--    - hashes identity email and compares it to the approved admin hash.
--
-- 2. Backup: MEETS-generated six-digit OTP delivered through Resend.
--    public.meets_admin_request_otp(text)
--    public.meets_admin_verify_otp(uuid,text)
--    - approved address stored only as SHA-256 hash;
--    - 10-minute expiry;
--    - max five failed attempts;
--    - one resend per 60 seconds;
--    - Resend sending-only key lives in Supabase Vault as meets_resend_api_key.
--
-- 3. Last resort: one-time high-entropy emergency recovery code.
--    public.meets_admin_recovery_login(text)
--    - plaintext recovery code is never stored;
--    - database keeps only SHA-256 hash;
--    - code is consumed on first successful use.
--
-- All successful methods issue the same short-lived MEETS admin session token.
-- Supabase Magic Link and password login are not part of the MEETS admin flow.
--
-- Production definitions must be inspected with pg_get_functiondef before changes.
-- Apply database changes via reviewed migrations.
